# ruff: noqa: E501
descriptions = {
    "active_geometry": "Geometry field name to which to restrict the processing (if not specified, all)",
    "active_layer": "Set active layer (if not specified, all)",
    "bbox": "Bounding box as xmin,ymin,xmax,ymax",
    "config": "Configuration option [may be repeated]",
    "creation_option": "Creation option [may be repeated]",
    "dialect": "SQL dialect",
    "features": "List all features (beware of RAM consumption on large layers). Mutually exclusive with 'summary'",
    "input_format": "Input formats [may be repeated], use short name from https://gdal.org/en/stable/drivers/vector/index.html",
    "input_layer": "Input layer name(s) [may be repeated]",
    "input_many": "Input vector datasets [may be repeated] [required], uses HDX resource_id UUID",
    "input": "Input vector dataset [required], uses HDX resource_id UUID",
    "layer_creation_option": "Layer creation option [may be repeated]",
    "limit": "Limit the number of features per layer (implies 'features')",
    "open_option": "Open option [may be repeated]",
    "output_format": "Output format, use short name from https://gdal.org/en/stable/drivers/vector/index.html",
    "output_layer": "Output layer name",
    "output_open_option": "Output open options [may be repeated]",
    "output": "Output vector dataset [required]",
    "preserve_boundary": "Whether the exterior boundary should be preserved",
    "skip_errors": "Skip errors when writing features",
    "sql": "Execute the indicated SQL statement and return the result. Mutually exclusive with 'input_layer'",
    "summary": "List the layer names and the geometry type. Mutually exclusive with 'features'",
    "tolerance": "Distance tolerance for simplification [required]",
    "where": "Attribute query in a restricted form of the queries used in the SQL WHERE statement",
}
